"""
Curated Local Model Catalog

Static catalog of GGUF models from official HuggingFace profiles (or trusted
community quantisers where the vendor does not publish GGUF).

Each entry carries the metadata the UI needs: download size, RAM requirement,
categories, quality/speed tier, and the exact HuggingFace coordinates for
one-click download.

RAM cap: 64 GB — models requiring more than 64 GB are excluded.
"""

from typing import Dict, List, Optional

# ── Category definitions ────────────────────────────────────────────────────

MODEL_CATEGORIES = {
    "general":      {"label": "General",      "icon": "MessageSquare", "description": "General-purpose chat and tasks"},
    "reasoning":    {"label": "Reasoning",    "icon": "Brain",         "description": "Logic, math, analysis"},
    "coding":       {"label": "Coding",       "icon": "Code",          "description": "Programming and code generation"},
    "creative":     {"label": "Creative",     "icon": "Palette",       "description": "Creative writing, storytelling"},
    "multilingual": {"label": "Multilingual", "icon": "Globe",         "description": "Strong non-English language support"},
    "vision":       {"label": "Vision",       "icon": "Eye",           "description": "Image understanding (multimodal)"},
}

# ── Quality / Speed tiers ───────────────────────────────────────────────────

QUALITY_TIERS = ("basic", "good", "great", "best")
SPEED_TIERS   = ("fast", "medium", "slow")

# ── The Catalog ─────────────────────────────────────────────────────────────

LOCAL_MODEL_CATALOG: List[Dict] = [
    # ── Qwen (Official GGUF) ───────────────────────────────────────────────
    {
        "id": "qwen2.5-0.5b",
        "name": "Qwen 2.5 0.5B",
        "family": "qwen",
        "provider": "Qwen",
        "parameter_size": "0.5B",
        "parameter_count": 0.5,
        "size_gb": 0.4,
        "ram_required_gb": 1,
        "ram_recommended_gb": 2,
        "categories": ["general"],
        "description": "Ultra-light model for basic tasks. Runs on any machine.",
        "quantization": "Q4_K_M",
        "context_window": 32768,
        "supports_vision": False,
        "supports_tools": False,
        "quality_tier": "basic",
        "speed_tier": "fast",
        "hf_repo": "Qwen/Qwen2.5-0.5B-Instruct-GGUF",
        "hf_filename": "qwen2.5-0.5b-instruct-q4_k_m.gguf",
        "chat_template": "chatml",
    },
    {
        "id": "qwen2.5-1.5b",
        "name": "Qwen 2.5 1.5B",
        "family": "qwen",
        "provider": "Qwen",
        "parameter_size": "1.5B",
        "parameter_count": 1.5,
        "size_gb": 1.0,
        "ram_required_gb": 2,
        "ram_recommended_gb": 4,
        "categories": ["general", "multilingual"],
        "description": "Compact multilingual model. Good for quick Q&A.",
        "quantization": "Q4_K_M",
        "context_window": 32768,
        "supports_vision": False,
        "supports_tools": False,
        "quality_tier": "basic",
        "speed_tier": "fast",
        "hf_repo": "Qwen/Qwen2.5-1.5B-Instruct-GGUF",
        "hf_filename": "qwen2.5-1.5b-instruct-q4_k_m.gguf",
        "chat_template": "chatml",
    },
    {
        "id": "qwen2.5-3b",
        "name": "Qwen 2.5 3B",
        "family": "qwen",
        "provider": "Qwen",
        "parameter_size": "3B",
        "parameter_count": 3.0,
        "size_gb": 2.0,
        "ram_required_gb": 4,
        "ram_recommended_gb": 6,
        "categories": ["general", "multilingual"],
        "description": "Solid small model for everyday tasks. Multilingual.",
        "quantization": "Q4_K_M",
        "context_window": 32768,
        "supports_vision": False,
        "supports_tools": True,
        "quality_tier": "good",
        "speed_tier": "fast",
        "hf_repo": "Qwen/Qwen2.5-3B-Instruct-GGUF",
        "hf_filename": "qwen2.5-3b-instruct-q4_k_m.gguf",
        "chat_template": "chatml",
    },
    {
        "id": "qwen2.5-7b",
        "name": "Qwen 2.5 7B",
        "family": "qwen",
        "provider": "Qwen",
        "parameter_size": "7B",
        "parameter_count": 7.0,
        "size_gb": 4.7,
        "ram_required_gb": 8,
        "ram_recommended_gb": 10,
        "categories": ["general", "multilingual"],
        "description": "Strong general-purpose model with excellent multilingual support.",
        "quantization": "Q4_K_M",
        "context_window": 131072,
        "supports_vision": False,
        "supports_tools": True,
        "quality_tier": "good",
        "speed_tier": "fast",
        "hf_repo": "Qwen/Qwen2.5-7B-Instruct-GGUF",
        "hf_filename": "qwen2.5-7b-instruct-q4_k_m.gguf",
        "chat_template": "chatml",
    },
    {
        "id": "qwen2.5-14b",
        "name": "Qwen 2.5 14B",
        "family": "qwen",
        "provider": "Qwen",
        "parameter_size": "14B",
        "parameter_count": 14.0,
        "size_gb": 9.0,
        "ram_required_gb": 12,
        "ram_recommended_gb": 16,
        "categories": ["general", "reasoning", "multilingual"],
        "description": "High-quality reasoning and multilingual model. Great balance of speed and capability.",
        "quantization": "Q4_K_M",
        "context_window": 131072,
        "supports_vision": False,
        "supports_tools": True,
        "quality_tier": "great",
        "speed_tier": "medium",
        "hf_repo": "Qwen/Qwen2.5-14B-Instruct-GGUF",
        "hf_filename": "qwen2.5-14b-instruct-q4_k_m.gguf",
        "chat_template": "chatml",
    },
    {
        "id": "qwen2.5-32b",
        "name": "Qwen 2.5 32B",
        "family": "qwen",
        "provider": "Qwen",
        "parameter_size": "32B",
        "parameter_count": 32.0,
        "size_gb": 20.0,
        "ram_required_gb": 24,
        "ram_recommended_gb": 32,
        "categories": ["general", "reasoning", "multilingual"],
        "description": "Top-tier reasoning with deep multilingual understanding.",
        "quantization": "Q4_K_M",
        "context_window": 131072,
        "supports_vision": False,
        "supports_tools": True,
        "quality_tier": "best",
        "speed_tier": "medium",
        "hf_repo": "Qwen/Qwen2.5-32B-Instruct-GGUF",
        "hf_filename": "qwen2.5-32b-instruct-q4_k_m.gguf",
        "chat_template": "chatml",
    },
    # ── Qwen Coder (Official GGUF) ─────────────────────────────────────────
    {
        "id": "qwen2.5-coder-7b",
        "name": "Qwen 2.5 Coder 7B",
        "family": "qwen",
        "provider": "Qwen",
        "parameter_size": "7B",
        "parameter_count": 7.0,
        "size_gb": 4.7,
        "ram_required_gb": 8,
        "ram_recommended_gb": 10,
        "categories": ["coding"],
        "description": "Specialised coding model. Excellent for code generation and review.",
        "quantization": "Q4_K_M",
        "context_window": 131072,
        "supports_vision": False,
        "supports_tools": True,
        "quality_tier": "good",
        "speed_tier": "fast",
        "hf_repo": "Qwen/Qwen2.5-Coder-7B-Instruct-GGUF",
        "hf_filename": "qwen2.5-coder-7b-instruct-q4_k_m.gguf",
        "chat_template": "chatml",
    },
    {
        "id": "qwen2.5-coder-14b",
        "name": "Qwen 2.5 Coder 14B",
        "family": "qwen",
        "provider": "Qwen",
        "parameter_size": "14B",
        "parameter_count": 14.0,
        "size_gb": 9.0,
        "ram_required_gb": 12,
        "ram_recommended_gb": 16,
        "categories": ["coding"],
        "description": "Advanced coding model for complex codebases and refactoring.",
        "quantization": "Q4_K_M",
        "context_window": 131072,
        "supports_vision": False,
        "supports_tools": True,
        "quality_tier": "great",
        "speed_tier": "medium",
        "hf_repo": "Qwen/Qwen2.5-Coder-14B-Instruct-GGUF",
        "hf_filename": "qwen2.5-coder-14b-instruct-q4_k_m.gguf",
        "chat_template": "chatml",
    },
    {
        "id": "qwen2.5-coder-32b",
        "name": "Qwen 2.5 Coder 32B",
        "family": "qwen",
        "provider": "Qwen",
        "parameter_size": "32B",
        "parameter_count": 32.0,
        "size_gb": 20.0,
        "ram_required_gb": 24,
        "ram_recommended_gb": 32,
        "categories": ["coding"],
        "description": "Best-in-class open coding model. Rivals proprietary coding assistants.",
        "quantization": "Q4_K_M",
        "context_window": 131072,
        "supports_vision": False,
        "supports_tools": True,
        "quality_tier": "best",
        "speed_tier": "medium",
        "hf_repo": "Qwen/Qwen2.5-Coder-32B-Instruct-GGUF",
        "hf_filename": "qwen2.5-coder-32b-instruct-q4_k_m.gguf",
        "chat_template": "chatml",
    },
    # ── Google Gemma 3 (Community GGUF — bartowski) ─────────────────────────
    {
        "id": "gemma3-1b",
        "name": "Gemma 3 1B",
        "family": "gemma",
        "provider": "Google",
        "parameter_size": "1B",
        "parameter_count": 1.0,
        "size_gb": 0.8,
        "ram_required_gb": 2,
        "ram_recommended_gb": 3,
        "categories": ["general"],
        "description": "Google's tiniest Gemma. Ultra-fast for simple tasks.",
        "quantization": "Q4_K_M",
        "context_window": 32768,
        "supports_vision": False,
        "supports_tools": False,
        "quality_tier": "basic",
        "speed_tier": "fast",
        "hf_repo": "bartowski/google_gemma-3-1b-it-GGUF",
        "hf_filename": "google_gemma-3-1b-it-Q4_K_M.gguf",
        "chat_template": "gemma",
    },
    # ── Google Gemma 3 (Official GGUF — Q4_0 QAT) ──────────────────────────
    {
        "id": "gemma3-4b",
        "name": "Gemma 3 4B",
        "family": "gemma",
        "provider": "Google",
        "parameter_size": "4B",
        "parameter_count": 4.0,
        "size_gb": 2.5,
        "ram_required_gb": 4,
        "ram_recommended_gb": 6,
        "categories": ["general", "multilingual"],
        "description": "Google's compact model. Fast and efficient for everyday tasks.",
        "quantization": "Q4_0",
        "context_window": 131072,
        "supports_vision": False,
        "supports_tools": False,
        "quality_tier": "good",
        "speed_tier": "fast",
        "hf_repo": "google/gemma-3-4b-it-qat-q4_0-gguf",
        "hf_filename": "gemma-3-4b-it-qat-q4_0.gguf",
        "chat_template": "gemma",
    },
    {
        "id": "gemma3-12b",
        "name": "Gemma 3 12B",
        "family": "gemma",
        "provider": "Google",
        "parameter_size": "12B",
        "parameter_count": 12.0,
        "size_gb": 7.2,
        "ram_required_gb": 10,
        "ram_recommended_gb": 12,
        "categories": ["general", "reasoning", "multilingual"],
        "description": "Strong mid-range model from Google. Excellent reasoning.",
        "quantization": "Q4_0",
        "context_window": 131072,
        "supports_vision": False,
        "supports_tools": False,
        "quality_tier": "great",
        "speed_tier": "medium",
        "hf_repo": "google/gemma-3-12b-it-qat-q4_0-gguf",
        "hf_filename": "gemma-3-12b-it-qat-q4_0.gguf",
        "chat_template": "gemma",
    },
    {
        "id": "gemma3-27b",
        "name": "Gemma 3 27B",
        "family": "gemma",
        "provider": "Google",
        "parameter_size": "27B",
        "parameter_count": 27.0,
        "size_gb": 16.0,
        "ram_required_gb": 20,
        "ram_recommended_gb": 24,
        "categories": ["general", "reasoning", "multilingual"],
        "description": "Google's most capable open model. Excellent across all tasks.",
        "quantization": "Q4_0",
        "context_window": 131072,
        "supports_vision": False,
        "supports_tools": False,
        "quality_tier": "best",
        "speed_tier": "slow",
        "hf_repo": "google/gemma-3-27b-it-qat-q4_0-gguf",
        "hf_filename": "gemma-3-27b-it-qat-q4_0.gguf",
        "chat_template": "gemma",
    },
    # ── Microsoft Phi-4 (Official GGUF) ─────────────────────────────────────
    {
        "id": "phi4-14b",
        "name": "Phi-4 14B",
        "family": "phi",
        "provider": "Microsoft",
        "parameter_size": "14B",
        "parameter_count": 14.0,
        "size_gb": 8.4,
        "ram_required_gb": 12,
        "ram_recommended_gb": 16,
        "categories": ["reasoning", "coding"],
        "description": "Microsoft's reasoning powerhouse. Punches well above its weight.",
        "quantization": "Q4_K_M",
        "context_window": 16384,
        "supports_vision": False,
        "supports_tools": True,
        "quality_tier": "great",
        "speed_tier": "medium",
        "hf_repo": "microsoft/phi-4-gguf",
        "hf_filename": "phi-4-q4.gguf",
        "chat_template": "phi",
    },
    # ── Meta Llama 3.2 (Community GGUF — bartowski) ─────────────────────────
    {
        "id": "llama3.2-1b",
        "name": "Llama 3.2 1B",
        "family": "llama",
        "provider": "Meta",
        "parameter_size": "1B",
        "parameter_count": 1.0,
        "size_gb": 0.7,
        "ram_required_gb": 2,
        "ram_recommended_gb": 3,
        "categories": ["general"],
        "description": "Meta's tiniest Llama. Ultra-fast for simple tasks.",
        "quantization": "Q4_K_M",
        "context_window": 131072,
        "supports_vision": False,
        "supports_tools": False,
        "quality_tier": "basic",
        "speed_tier": "fast",
        "hf_repo": "bartowski/Llama-3.2-1B-Instruct-GGUF",
        "hf_filename": "Llama-3.2-1B-Instruct-Q4_K_M.gguf",
        "chat_template": "llama3",
    },
    {
        "id": "llama3.2-3b",
        "name": "Llama 3.2 3B",
        "family": "llama",
        "provider": "Meta",
        "parameter_size": "3B",
        "parameter_count": 3.0,
        "size_gb": 2.0,
        "ram_required_gb": 4,
        "ram_recommended_gb": 6,
        "categories": ["general", "multilingual"],
        "description": "Versatile small model from Meta. Great everyday assistant.",
        "quantization": "Q4_K_M",
        "context_window": 131072,
        "supports_vision": False,
        "supports_tools": True,
        "quality_tier": "good",
        "speed_tier": "fast",
        "hf_repo": "bartowski/Llama-3.2-3B-Instruct-GGUF",
        "hf_filename": "Llama-3.2-3B-Instruct-Q4_K_M.gguf",
        "chat_template": "llama3",
    },
    # ── Meta Llama 3.1 (Community GGUF — bartowski) ─────────────────────────
    {
        "id": "llama3.1-8b",
        "name": "Llama 3.1 8B",
        "family": "llama",
        "provider": "Meta",
        "parameter_size": "8B",
        "parameter_count": 8.0,
        "size_gb": 4.9,
        "ram_required_gb": 8,
        "ram_recommended_gb": 10,
        "categories": ["general", "multilingual"],
        "description": "Meta's workhorse model. Strong all-rounder with 128K context.",
        "quantization": "Q4_K_M",
        "context_window": 131072,
        "supports_vision": False,
        "supports_tools": True,
        "quality_tier": "good",
        "speed_tier": "fast",
        "hf_repo": "bartowski/Meta-Llama-3.1-8B-Instruct-GGUF",
        "hf_filename": "Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf",
        "chat_template": "llama3",
    },
    {
        "id": "llama3.1-70b",
        "name": "Llama 3.1 70B",
        "family": "llama",
        "provider": "Meta",
        "parameter_size": "70B",
        "parameter_count": 70.0,
        "size_gb": 40.0,
        "ram_required_gb": 48,
        "ram_recommended_gb": 56,
        "categories": ["general", "reasoning", "multilingual"],
        "description": "Meta's flagship. Near-frontier performance, fully local.",
        "quantization": "Q4_K_M",
        "context_window": 131072,
        "supports_vision": False,
        "supports_tools": True,
        "quality_tier": "best",
        "speed_tier": "slow",
        "hf_repo": "bartowski/Meta-Llama-3.1-70B-Instruct-GGUF",
        "hf_filename": "Meta-Llama-3.1-70B-Instruct-Q4_K_M.gguf",
        "chat_template": "llama3",
    },
    # ── Mistral (Community GGUF — bartowski) ────────────────────────────────
    {
        "id": "mistral-7b",
        "name": "Mistral 7B",
        "family": "mistral",
        "provider": "Mistral AI",
        "parameter_size": "7B",
        "parameter_count": 7.0,
        "size_gb": 4.1,
        "ram_required_gb": 8,
        "ram_recommended_gb": 10,
        "categories": ["general"],
        "description": "Efficient European model with strong general capabilities.",
        "quantization": "Q4_K_M",
        "context_window": 32768,
        "supports_vision": False,
        "supports_tools": True,
        "quality_tier": "good",
        "speed_tier": "fast",
        "hf_repo": "bartowski/Mistral-7B-Instruct-v0.3-GGUF",
        "hf_filename": "Mistral-7B-Instruct-v0.3-Q4_K_M.gguf",
        "chat_template": "mistral",
    },
    {
        "id": "mistral-small-22b",
        "name": "Mistral Small 22B",
        "family": "mistral",
        "provider": "Mistral AI",
        "parameter_size": "22B",
        "parameter_count": 22.0,
        "size_gb": 13.0,
        "ram_required_gb": 16,
        "ram_recommended_gb": 20,
        "categories": ["general", "reasoning"],
        "description": "Mistral's mid-range model. Great reasoning at moderate size.",
        "quantization": "Q4_K_M",
        "context_window": 32768,
        "supports_vision": False,
        "supports_tools": True,
        "quality_tier": "great",
        "speed_tier": "medium",
        "hf_repo": "bartowski/Mistral-Small-24B-Instruct-2501-GGUF",
        "hf_filename": "Mistral-Small-24B-Instruct-2501-Q4_K_M.gguf",
        "chat_template": "mistral",
    },
    # ── DeepSeek R1 Distill (Community GGUF — bartowski) ────────────────────
    {
        "id": "deepseek-r1-1.5b",
        "name": "DeepSeek R1 1.5B",
        "family": "deepseek",
        "provider": "DeepSeek",
        "parameter_size": "1.5B",
        "parameter_count": 1.5,
        "size_gb": 1.0,
        "ram_required_gb": 2,
        "ram_recommended_gb": 4,
        "categories": ["reasoning"],
        "description": "Tiny reasoning model. Surprisingly capable for its size.",
        "quantization": "Q4_K_M",
        "context_window": 65536,
        "supports_vision": False,
        "supports_tools": False,
        "quality_tier": "basic",
        "speed_tier": "fast",
        "hf_repo": "bartowski/DeepSeek-R1-Distill-Qwen-1.5B-GGUF",
        "hf_filename": "DeepSeek-R1-Distill-Qwen-1.5B-Q4_K_M.gguf",
        "chat_template": "chatml",
    },
    {
        "id": "deepseek-r1-7b",
        "name": "DeepSeek R1 7B",
        "family": "deepseek",
        "provider": "DeepSeek",
        "parameter_size": "7B",
        "parameter_count": 7.0,
        "size_gb": 4.7,
        "ram_required_gb": 8,
        "ram_recommended_gb": 10,
        "categories": ["reasoning", "coding"],
        "description": "Strong reasoning model with chain-of-thought. Great for analysis.",
        "quantization": "Q4_K_M",
        "context_window": 65536,
        "supports_vision": False,
        "supports_tools": False,
        "quality_tier": "good",
        "speed_tier": "fast",
        "hf_repo": "bartowski/DeepSeek-R1-Distill-Qwen-7B-GGUF",
        "hf_filename": "DeepSeek-R1-Distill-Qwen-7B-Q4_K_M.gguf",
        "chat_template": "chatml",
    },
    {
        "id": "deepseek-r1-14b",
        "name": "DeepSeek R1 14B",
        "family": "deepseek",
        "provider": "DeepSeek",
        "parameter_size": "14B",
        "parameter_count": 14.0,
        "size_gb": 8.9,
        "ram_required_gb": 12,
        "ram_recommended_gb": 16,
        "categories": ["reasoning", "coding"],
        "description": "Excellent reasoning model. Shows its chain of thought step by step.",
        "quantization": "Q4_K_M",
        "context_window": 65536,
        "supports_vision": False,
        "supports_tools": False,
        "quality_tier": "great",
        "speed_tier": "medium",
        "hf_repo": "bartowski/DeepSeek-R1-Distill-Qwen-14B-GGUF",
        "hf_filename": "DeepSeek-R1-Distill-Qwen-14B-Q4_K_M.gguf",
        "chat_template": "chatml",
    },
    {
        "id": "deepseek-r1-32b",
        "name": "DeepSeek R1 32B",
        "family": "deepseek",
        "provider": "DeepSeek",
        "parameter_size": "32B",
        "parameter_count": 32.0,
        "size_gb": 19.0,
        "ram_required_gb": 24,
        "ram_recommended_gb": 32,
        "categories": ["reasoning", "coding"],
        "description": "Top-tier reasoning. Competes with much larger proprietary models.",
        "quantization": "Q4_K_M",
        "context_window": 65536,
        "supports_vision": False,
        "supports_tools": False,
        "quality_tier": "best",
        "speed_tier": "medium",
        "hf_repo": "bartowski/DeepSeek-R1-Distill-Qwen-32B-GGUF",
        "hf_filename": "DeepSeek-R1-Distill-Qwen-32B-Q4_K_M.gguf",
        "chat_template": "chatml",
    },
    {
        "id": "deepseek-r1-70b",
        "name": "DeepSeek R1 70B",
        "family": "deepseek",
        "provider": "DeepSeek",
        "parameter_size": "70B",
        "parameter_count": 70.0,
        "size_gb": 42.0,
        "ram_required_gb": 48,
        "ram_recommended_gb": 56,
        "categories": ["reasoning", "coding"],
        "description": "The full DeepSeek R1 distill. Frontier-class reasoning, fully local.",
        "quantization": "Q4_K_M",
        "context_window": 65536,
        "supports_vision": False,
        "supports_tools": False,
        "quality_tier": "best",
        "speed_tier": "slow",
        "hf_repo": "bartowski/DeepSeek-R1-Distill-Llama-70B-GGUF",
        "hf_filename": "DeepSeek-R1-Distill-Llama-70B-Q4_K_M.gguf",
        "chat_template": "llama3",
    },
]

# ── Lookup index ────────────────────────────────────────────────────────────

_CATALOG_BY_ID: Dict[str, Dict] = {m["id"]: m for m in LOCAL_MODEL_CATALOG}

# ── Public helpers ──────────────────────────────────────────────────────────

RAM_CAP_GB = 64


def get_catalog(
    max_ram_gb: Optional[int] = None,
    category: Optional[str] = None,
) -> List[Dict]:
    """Return catalog entries, optionally filtered by RAM budget and category."""
    cap = min(max_ram_gb, RAM_CAP_GB) if max_ram_gb else RAM_CAP_GB
    results = []
    for m in LOCAL_MODEL_CATALOG:
        if m["ram_required_gb"] > cap:
            continue
        if category and category not in m["categories"]:
            continue
        results.append(m)
    return results


def get_model(model_id: str) -> Optional[Dict]:
    """Look up a single model by its catalog ID."""
    return _CATALOG_BY_ID.get(model_id)


def get_recommended(system_ram_gb: int, limit: int = 3) -> List[Dict]:
    """Pick the best models that fit comfortably in the user's RAM."""
    cap = min(system_ram_gb, RAM_CAP_GB)
    candidates = [
        m for m in LOCAL_MODEL_CATALOG
        if m["ram_recommended_gb"] <= cap
    ]
    tier_order = {t: i for i, t in enumerate(QUALITY_TIERS)}
    candidates.sort(
        key=lambda m: (-tier_order.get(m["quality_tier"], 0), -m["parameter_count"]),
    )
    return candidates[:limit]


def get_all_categories() -> List[Dict]:
    """Return category metadata."""
    return [
        {"id": k, **v}
        for k, v in MODEL_CATEGORIES.items()
    ]
